### ISSUE TITLE
No longer getting price updates

### ISSUE THREAD

**Issue by flyize** [samyun/southwest-price-drop-bot#12]
Is anyone else having this issue?  Seems to exist for current entries as well as new ones.

**Comment by samyun** [comment]
What version is deployed? See #4

**Comment by flyize** [comment]
The version was current as of a couple hours ago.  I see a new commit.  Any chance that would help?

**Comment by samyun** [comment]
No, I created a new release 3.1.1 with the semaphores, but that shouldn’t affect this. Mind posting some of the logs? Look for sections that say “error” or “warning”

**Comment by flyize** [comment]
I assume its this then (using Heroku if it matters):

May 07 08:51:32 fly app/scheduler.2320: Error: Failed to launch chrome! 
May 07 08:51:32 fly app/scheduler.2320: /app/node_modules/puppeteer/.local-chromium/linux-549031/chrome-linux/chrome: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory 
May 07 08:51:32 fly app/scheduler.2320: (node:20) UnhandledPromiseRejectionWarning: ReferenceError: browser is not defined 
May 07 08:51:32 fly app/scheduler.2320: (node:20) ReferenceError: browser is not defined

**Comment by samyun** [comment]
That would be it.

Is this a fresh deployment, or did you do the redeploy through Heroku?

**Comment by flyize** [comment]
Redeploy

**Comment by samyun** [comment]
Read through the readme. There’s a buildpack you need to add. One of the issues discussed this.

**Comment by samyun** [comment]
#4 actually.

**Comment by flyize** [comment]
Okay, I've added the buildpack, that error is gone, and it seems to be pulling prices for new alerts.  However, it still doesn't seem to be updating existing alerts.  Do they have to be removed and readded?

**Comment by samyun** [comment]
Anything in the logs?

**Comment by flyize** [comment]
Actually, no.  According to the Heroku scheduler, the task should have run at :50.  But this is the only thing I have in the logs around that time.

May 07 09:50:42 flysw app/heroku-redis:  source=REDIS sample#active-connections=3 sample#load-avg-1m=0.11 sample#load-avg-5m=0.09 sample#load-avg-15m=0.04 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15664184kB sample#memory-free=12564788kB sample#memory-cached=1633840kB sample#memory-redis=321056bytes sample#hit-rate=1 sample#evicted-keys=0

**Comment by samyun** [comment]
Looks like it didn’t run for some reason. It should check them the next round.

**Comment by flyize** [comment]
As expected, you are correct.  Thanks!
