### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by GC-Guy** [samyun/southwest-price-drop-bot#29]
Given the challenges with Heroku IPs being blocked, would it be feasible to add support for an optional proxy parameter? If we could feed in our own proxy or proxies to be used to query southwest.com, it could allow it to still run in heroku and just bounce off a proxy to bypass the IP block. This would also be useful in local mode or other cloud providers in case they get more aggressive on blocking IPs that send multiple queries.

**Comment by GC-Guy** [comment]
I sent in a PR for this feature. If anyone wants to spin up a quick proxy for themselves, you could do something like squid, either natively, in a VM, or in a container. I suggest port-forwarding to or running on a random high port, and locking down your squid.conf something like this:

```
acl swa dstdomain .southwest.com
http_access allow swa
http_access deny all

```
so people don't use you as an open proxy.

**Comment by samyun** [comment]
Completed with #32
