### ISSUE TITLE
Random user agent

### ISSUE THREAD

**Issue by GC-Guy** [samyun/southwest-price-drop-bot#31]
Seeing as how SWA blocked Heroku IPs, it's likely another step they will take is looking at User Agent strings and blocking specific ones. The default for Puppeteer is not stealthy, so it may be a good idea to get ahead of them and put in a list of the 10 or 20 most common UAs and randomly rotate through them. The function to do it is
`page.setUserAgent(userAgent)`
and docs are at https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetuseragentuseragent if someone gets bored.

**Comment by samyun** [comment]
I already do this in `lib/bot/get-price.js`:

 `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36');`

I figure Chrome is least likely to be flagged, being the most popular browser on the web.

**Comment by GC-Guy** [comment]
Wow, it was literally right in front of me, sorry I missed it.

**Comment by samyun** [comment]
No worries!
