### ISSUE TITLE
Proxy not working when running schedule

### ISSUE THREAD

**Issue by rbreneman** [samyun/southwest-price-drop-bot#33]
When running npm run task:check from the scheduler or from console it doesn't seem to be using the proxy settings. I see no connections on my proxy log. However from the app web interface, if I add a flight for the first time, or go back and edit/save, then it uses the proxy and completes the check successfully.

From the console I see Access Denied when it runs the check.

Thanks in advance for any help. This app is awesome!

**Comment by GC-Guy** [comment]
I submitted a PR with what I believe to be a valid fix. Good catch @rbreneman
