### ISSUE TITLE
TypeError: Plivo.RestAPI is not a function

### ISSUE THREAD

**Issue by ribordy** [samyun/southwest-price-drop-bot#39]
Running into this with a fresh install on master:
```
TypeError: Plivo.RestAPI is not a function
    at getPlivo (/home/ubuntu/southwest-price-drop-bot/lib/bot/send-sms.js:30:16)
    at Object.sendSms (/home/ubuntu/southwest-price-drop-bot/lib/bot/send-sms.js:10:17)
    at values.map.sort.map (/home/ubuntu/southwest-price-drop-bot/tasks/check.js:77:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Looks to be a result of jumping from `0.4.1` to `4.0.1` [here](https://github.com/samyun/southwest-price-drop-bot/commit/887f16b3ef035cf4278cd42f4b3b340a55207594#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L42). The API of that package changed between versions. Happy to open a PR to fix--seems that reverting to `0.4.1` will resolve things in the short term, but unsure if it's preferred to instead attempt to wholesale update all plivo references to use the new package's API

**Comment by minamhere** [comment]
I ran into this as well. The new API looks pretty easy to adopt. I started working on this and have it working in my fork, but something isn't quite right. I should have something I can share in the next couple days and will submit PR once I finish.

**Comment by ribordy** [comment]
@minamhere any luck? I've got some time in the next week or two to take a crack at this if you haven't already.

**Comment by tjs198** [comment]
Plivo has stopped working for me.  Mailgun still working well.  Anyone have a fix?

**Comment by ribordy** [comment]
@tjs198 just opened a PR to fix, once it gets merged in you should be able to update and regain SMS support.
