### ISSUE TITLE
Where do we add in "@GC-Guy's proxy support"?

### ISSUE THREAD

**Issue by honeytrek** [samyun/southwest-price-drop-bot#40]
Can that be entered in Heroku? Or somewhere else. Also how do we find out that proxy port as well.

Thanks so much guys for working on this awesome tool!

**Comment by tjs198** [comment]
Heroku has been working fine for me without any proxy support

**Comment by flyize** [comment]
Lucky you.  Doesn't work for me.

**Comment by samyun** [comment]
Settings tab, Config Vars, Key: PROXY, Value: <your proxy>. Proxy port is dependent on your proxy.
