### ISSUE TITLE
Deploy to Heroku Button broken

### ISSUE THREAD

**Issue by driscoll42** [samyun/southwest-price-drop-bot#52]
The button in the readme just links to https://heroku.com/deploy
when it needs to be https://dashboard.heroku.com/new?template=https%3A%2F%2Fgithub.com%2Fsamyun%2Fsouthwest-price-drop-bot%2F

**Comment by samyun** [comment]
Per the documentation https://devcenter.heroku.com/articles/heroku-button#creating-the-app-json-file:

> If you’re embedding the button in a GitHub repository’s README file, Heroku will automatically infer the repository URL from the referer header when someone clicks on the button.

> This is convenient because it avoids hard-coding the specific repository URL into the button, allowing forks and branches of the repository to work properly without a change to the button href.
