### ISSUE TITLE
Stuck on "Fetching price... Reload the page in a few minutes"

### ISSUE THREAD

**Issue by divincenzo** [samyun/southwest-price-drop-bot#53]
I'm trying the most recent update and I'm using a residential proxy from luminati, I do receive the text message that my flight is being monitored and it looks like "npm run task:check" is running every 10 minutes but im not getting a text notification on the price drop and status stays at "Fetching price... Reload the page in a few minutes"

**Comment by samyun** [comment]
If you look at the logs, is it actually succeeding at getting the prices?

**Comment by mastermind85** [comment]
I am having the same issues, is the bot completely dead now? Showing no errors in the logs but can't update the prices...

**Comment by samyun** [comment]
https://github.com/samyun/southwest-price-drop-bot/pull/60 should fix that
