### ISSUE TITLE
Mailgun alternatives?

### ISSUE THREAD

**Issue by samyun** [samyun/southwest-price-drop-bot#62]
Does anyone have any ideas for an alternative to Mailgun, now that it seems they’re getting rid of their free tier?

**Comment by iloveitaly** [comment]
I think MG still allows ~600 free emails per month, right? https://news.ycombinator.com/item?id=22192543

Send grid also has a nice free tier https://sendgrid.com/free/

**Comment by iloveitaly** [comment]
I added support for SMTP delivery as well here https://github.com/samyun/southwest-price-drop-bot/pull/69. Closing this out!
